name: HMA
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - backcall=0.1.0
  - cudatoolkit=10.0.130
  - decorator=4.4.2
  - entrypoints=0.3
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - libsodium=1.0.16
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyzmq=18.1.1
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - zeromq=4.3.1
  - blas=2.14
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - certifi=2020.6.20
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - gmp=6.2.0
  - gnutls=3.6.13
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5py=2.10.0
  - harfbuzz=2.4.0
  - hdf5=1.10.6
  - icu=64.2
  - jasper=1.900.1
  - jpeg=9d
  - lame=3.100
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libiconv=1.16
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.7
  - libopencv=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxkbcommon=0.10.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.0
  - nettle=3.4.1
  - nspr=4.28
  - nss=3.47
  - numpy=1.19.1
  - opencv=4.4.0
  - openh264=2.1.1
  - openssl=1.1.1g
  - pixman=0.38.0
  - py-opencv=4.4.0
  - pyqt=5.12.3
  - python_abi=3.7
  - qt=5.12.5
  - quaternion=2020.5.19.15.27.24
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - threadpoolctl=2.1.0
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.9.0
  - asn1crypto=1.3.0
  - astor=0.8.0
  - blinker=1.4
  - c-ares=1.15.0
  - cachetools=3.1.1
  - cffi=1.13.2
  - chardet=3.0.4
  - click=7.1.1
  - cryptography=2.8
  - dbus=1.13.12
  - expat=2.2.6
  - freetype=2.9.1
  - gast=0.2.2
  - glib=2.63.1
  - google-auth=1.13.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.27.2
  - idna=2.8
  - intel-openmp=2019.4
  - joblib=0.14.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libxcb=1.13
  - libxml2=2.9.9
  - llvmlite=0.31.0
  - markdown=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - ncurses=6.1
  - ninja=1.9.0
  - numba=0.48.0
  - numpy-base=1.18.5
  - oauthlib=3.1.0
  - olefile=0.46
  - opt_einsum=3.1.0
  - pandas=1.0.0
  - pcre=8.43
  - pillow=7.0.0
  - pip=20.0.2
  - protobuf=3.11.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.19
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=7.0
  - requests=2.22.0
  - requests-oauthlib=1.3.0
  - rsa=4.0
  - setuptools=45.1.0
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - tensorboard=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - termcolor=1.1.0
  - tk=8.6.8
  - urllib3=1.25.8
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pytorch=1.4.0
  - torchvision=0.5.0
  - pip:
    - -ensorflow==2.1.0
    - annoy==1.16.3
    - cycler==0.10.0
    - ffnet==0.8.4
    - kiwisolver==1.1.0
    - matplotlib==3.1.3
    - mocap==1.2.41
    - networkx==2.4
    - numpy-quaternion==2020.5.19.15.27.24
    - pyparsing==2.4.6
    - pyqt5==5.12.3
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pyyaml==5.3.1
    - seaborn==0.10.1
    - spacepy==0.2.2
    - tensorboardx==1.9
    - tensorflow==2.0.0
    - torch==1.4.0
    - torchlight==1.0
    - tqdm==4.42.1
    - transform3d==0.0.3
    - transforms3d==0.3.1

